version: "3.3"
services:
    monitoring:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: monitoring
        restart: always
        volumes:
            - ./:/app
        ports:
            - "7000:5000"